### ISSUE TITLE
Getting SQL80001: Incorrect syntax near '[CredentialName]'.  Expecting '='.

### ISSUE THREAD

**Issue by tomas-weir** [MicrosoftDocs/sql-docs#2549]
Using SSDT:

CREATE DATABASE SCOPED CREDENTIAL [CredentialName] WITH IDENTITY = 'Something',   
    SECRET = '&lt;EnterStrongPasswordHere&gt;';  
GO  

I get error: "SQL80001: Incorrect syntax near '[CredentialName]'.  Expecting '='."

Intellisence in SSMS shows the same syntax issue but then executes the command successfully.

Environment:
- Microsoft SQL Azure (RTM) - 12.0.2000.8
- Microsoft Visual Studio Professional 2017 Version 15.9.14
- SQL Server Data Tools  15.1.61906.03120

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140d7c84-acc3-f722-99af-867be1f8752a
* Version Independent ID: 6bb40855-9644-1b18-3c4f-cec734cdc169
* Content: [CREATE DATABASE SCOPED CREDENTIAL (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-scoped-credential-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-database-scoped-credential-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-database-scoped-credential-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by tomas-weir** [comment]
Probably no issue with the docs. It's a VS issue. Upgraded to latest 2019 but having the same issue. I can see people have been reporting that same issue since 2016...

**Comment by VanMSFT** [comment]
@tomas-weir - Thanks for bringing this issue up! Yes, this is a Product/Support issue and I would advise that you look through the following channels for support if you haven't already done so. Thanks!

- [UserVoice - Suggestion to improve SQL Server?](https://feedback.azure.com/forums/908035-sql-server)
- [Setup and Upgrade -  MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsetupandupgrade&filter=alltypes&sort=lastpostdesc)
- [SQL Server Data Tools - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=ssdt&filter=alltypes&sort=lastpostdesc)
- [Transact-SQL - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=transactsql)
- [SQL Server Security -  MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsecurity&filter=alltypes&sort=lastpostdesc)
- [DBA Stack Exchange (tag sql-server) - ask SQL Server questions](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow (tag sql-server) - also has some answers about SQL development](https://stackoverflow.com/questions/tagged/sql-server) 
- [Reddit - general discussion about SQL Server](https://www.reddit.com/r/SQLServer/)
- [Microsoft SQL Server License Terms and Information](https://www.microsoft.com/download/details.aspx?id=39299)
- [Support options for business users](https://support.microsoft.com/gp/support-options-for-business)
- [Contact Microsoft](https://support.microsoft.com/gp/contactus81?Audience=Commercial)
- [All the ways to get help](https://docs.microsoft.com/sql/sql-server/sql-server-get-help)

**Comment by aszalacinski** [comment]
This being closed and not being answered is lazy on MS part. If common errors are not addressed in documentation then this documentation is useless.

**Comment by leonardobravo-utilities** [comment]
Same problem here

**Comment by abbgrade** [comment]
This bug is still present in Visual Studio 2019

**Comment by blakeh1** [comment]
This is still a problem in Visual Studio 2022. Not sure how were are expected to keep using tools that do not work. That link above claims it is an intellisense issue that does not prevent compiling. However it does prevent building in both 2019 and 2022

**Comment by AutomateVisual2022** [comment]
Hi All,
working on Visual 2022, and keep on seeing this issues for SQL Azure scripts. The script works without any issues in sql studio.
SQL46010: Incorrect syntax near CATALOG_COLLATION , SQL80001: Incorrect syntax near ','. We need to compile and clear all syntax errors on Visual studio 2022 to build a pipeline on Azure portal. Do we have any resolution to resolve the errors and compile to get a scripty with out any errors on visual studio.

**Comment by jonathan-vargas-sdbullion** [comment]
Any help on this will be appreciated!

**Comment by AutomateVisual2022** [comment]
On Visual , change your .sql file from .sln project as Build=NOne.

**Comment by Backeman** [comment]
I have the same issue. Getting a syntax warning in Visual Studio 2022, Management Studio and when I try to build it via a Pipeline in DevOps. But I can run the command manually through Management Studio successfully. 

![image](https://user-images.githubusercontent.com/10833181/189103564-2b9c2676-6d9e-40d2-bfde-f3a08be09973.png)

**Comment by AutomateVisual2022** [comment]
> I have the same issue. Getting a syntax warning in Visual Studio 2022, Management Studio and when I try to build it via a Pipeline in DevOps. But I can run the command manually through Management Studio successfully.
> 
> ![image](https://user-images.githubusercontent.com/10833181/189103564-2b9c2676-6d9e-40d2-bfde-f3a08be09973.png)

Yes, these scripts will be successfully execute on management studio as well as in visual studio but on the Pipeline release you will see these errrors. As a work around ,we had to change the property of .sql file on visual studio project as "Build=none" and published to devops repository, in repo for sql project->ItemGroup->Build Include and triggered the release to get it worked. you can try .

**Comment by Backeman** [comment]
Hi, thanks for the reply. I don't really get what you have done. 

I've tried to set is a Build=none locally, but that means the External Data Source I've defined gets pissed and don't have a Credential to use => More build errors. 

Are you saying I should set all files cascading down from the Credential to Build=None, and then with some settings in the pipeline, get the release to include these files anyway?

**Comment by AutomateVisual2022** [comment]
> Hi, thanks for the reply. I don't really get what you have done.
> 
> I've tried to set is a Build=none locally, but that means the External Data Source I've defined gets pissed and don't have a Credential to use => More build errors.
> 
> Are you saying I should set all files cascading down from the Credential to Build=None, and then with some settings in the pipeline, get the release to include these files anyway?

yes, set all files to Build=None and if you are using SQL project check in your SQL project properties in visual studio is using the latest Azure SQL verson and then do a rebuild.

**Comment by Backeman** [comment]
> > Hi, thanks for the reply. I don't really get what you have done.
> > I've tried to set is a Build=none locally, but that means the External Data Source I've defined gets pissed and don't have a Credential to use => More build errors.
> > Are you saying I should set all files cascading down from the Credential to Build=None, and then with some settings in the pipeline, get the release to include these files anyway?
> 
> yes, set all files to Build=None and if you are using SQL project check in your SQL project properties in visual studio is using the latest Azure SQL verson and then do a rebuild.

I understand the part up until I'm checking it into the repo. 

What I didn't understand is how you "reverse" it when building it in DevOps? Because, I guess that if you set build=none, it won't be included in the final product that is deployed, or am I missing something?

**Comment by AutomateVisual2022** [comment]
> > > Hi, thanks for the reply. I don't really get what you have done.
> > > I've tried to set is a Build=none locally, but that means the External Data Source I've defined gets pissed and don't have a Credential to use => More build errors.
> > > Are you saying I should set all files cascading down from the Credential to Build=None, and then with some settings in the pipeline, get the release to include these files anyway?
> > 
> > 
> > yes, set all files to Build=None and if you are using SQL project check in your SQL project properties in visual studio is using the latest Azure SQL verson and then do a rebuild.
> 
> I understand the part up until I'm checking it into the repo.
> 
> What I didn't understand is how you "reverse" it when building it in DevOps? Because, I guess that if you set build=none, it won't be included in the final product that is deployed, or am I missing something?

Once you rebuild and checkedin to the repo, from repo edit the .sqlproj ItemGroup file to <Build Include> this will work

**Comment by pixmeister** [comment]
Issue still live in VS 2022. Can't build a DB Project. How is this even closed with not even a viable workaround????

**Comment by Fasteroid** [comment]
@VanMSFT clearly since you closed the issue, you must know of a workaround or fix for it—could you give us a more direct link or description of the workaround?

If not, _why is this issue closed?_
